### ISSUE TITLE
HTML5

### ISSUE THREAD

**Issue by say2joe** [lucidlemon/paradeiser#1]
Please update your markup when you have the time. I'm starting to get frustrated by so many people (not the author of this great menu package) who neglect more semantic markup in favor of "DIVitus". For example, you could replace `<div class="paradeiser"></div>` with `<nav class="paradeiser"></nav>`.

Nice work on this great "menu-maker" and great job at keeping it simple and slim! #awesome-job

**Comment by lucidlemon** [comment]
whoops. thanks a lot for pointing this out.
Will fix this asap.
