### ISSUE TITLE
Paradeiser not Rendering Correctly on Chrome/Safari for iPhone

### ISSUE THREAD

**Issue by TheoBearman** [lucidlemon/paradeiser#11]
Paradeiser seems to have a rendering problem in both Chrome and Safari for iPhone. I have not checked this in other iOS browsers that are avaliable however I can confirm Paradeiser does work in Chrome for Android having been checked by @pierr3.

Screenshot from Chrome for iOS is below. The behaviour is similar in Safari.

![img_4102](https://cloud.githubusercontent.com/assets/6546590/9629063/d5098f9c-5167-11e5-8d65-7fbf28880c40.PNG)

**Comment by lucidlemon** [comment]
As mentioned on twitter please download the new CSS version or use the minified one. I forgot to vendor-prefix the css until v0.2.7

**Comment by TheoBearman** [comment]
@lucidlemon I am on v0.2.9 now and this issue is still occurring. I haven't tried the minified version. Would that make a difference?

EDIT: It is rendering in Safari which makes me think that Chrome is just using a cached version of the CSS file that was pre-v0.2.7. I will update if this is not the case.

**Comment by lucidlemon** [comment]
I can not see any prefix seen [here](https://github.com/lucidlemon/paradeiser/blob/master/dist/paradeiser.css) like the

``` css
  display: -webkit-box;
  display: -webkit-flex;
  display: -ms-flexbox;
  display: flex;
```

on lines 21 to 24 in your [included css](https://vatsim.theobearman.com/css/paradeiser.css), are you sure you have uploaded the correct version?

edit: I also see that you seem to use cloudflare, maybe it's a cache problem?

**Comment by TheoBearman** [comment]
@lucidlemon See the update above.

**Comment by lucidlemon** [comment]
chrome does not have any problems as chrome doesn't need flexbox to be prefixed, that's why chrome is always working, no matter which version of paradeiser you use.
Safari however needs the prefixes, and I included them into the .min file since the initial release, but I forgot to add it to the non min until 0.2.7, so if safari gets the 0.2.9 soon, it won't be a problem.
Or do you mean that safari is already rendering it correct on your devices?

**Comment by TheoBearman** [comment]
@lucidlemon I have refreshed the cache and made sure that the version of the CSS is current. The issue has been solved both on Chrome and Safari.

**Comment by lucidlemon** [comment]
perfect!
