### ISSUE TITLE
`.paradeiser_dropdown` can't be a `<span>` element.

### ISSUE THREAD

**Issue by geoffreycrofte** [lucidlemon/paradeiser#13]
Hello,

The `<span class="paradeiser_dropdown">` can't be a SPAN element because it's not valid to have an UL element inside.
HTML basics :)

Good luck.

**Comment by lucidlemon** [comment]
oh whoops! you are right!

i will fix this as soon as html validation becomes relevant! see you in 1994!

—
Daniel Winterdanielwinter.at

**Comment by lucidlemon** [comment]
and fyi
https://validator.w3.org/nu/?doc=http%3A%2F%2Fwww.google.com%2F
not even google has valid html.  html basics = rules are meant to be broken. as long as they don't give us an unstyled block link i will never ever respect html validation.

**Comment by geoffreycrofte** [comment]
I know that lot of great websites are wrong.
It's not because Google is wrong that we must imitate him.
In your case you can do the same thing easily being W3C compliant :)
Thank you.

**Comment by lucidlemon** [comment]
I don't know if 1% of the top 1000 websites would pass validation and I highly doubt it. It is also not valid to put an image (= icon) into an `<a>` tag, but there is no other element that supports `href` natively, so I would have to parse it via JS to make it HTML valid. This alone show how old and bad these rules are.
Every Browser support is the way it should, and it is not a broken markup like `<a><span></a></span>` would be, it's just used in a different styling way. And semantically span and div have absolutely 0 meaning.

You are therefore free to change the markup in your own project, but I will not rewrite it in here as I see no reason to do so.

**Comment by viniciuskneves** [comment]
@creativejuiz you could also PR it

**Comment by geoffreycrofte** [comment]
Yeah, I could, but I don't want to spend my time if @lucidlemon does not 
agree with the change.
He is right, he can propose an invalid code for everyone, I'll use a 
valid one in case of need. :)
