### ISSUE TITLE
Providing Paradeiser over a CDN

### ISSUE THREAD

**Issue by TheoBearman** [lucidlemon/paradeiser#14]
Hey there,

I'm happy to see there is fairly consistent updating of Paradeiser. Having said that, it's quite a hassle to keep redownloading a CSS file and uploading it to my server every time there is an update. Consequently, is it possible to have Paradeiser hosted on a CDN?

Thanks,

Theo

**Comment by lucidlemon** [comment]
Hi,
totally an option, I'll look around where to host scripts like this one.
And yeah, sure I try to improve each and every bit, as this should be the reason to use a small set of features like Paradeiser provides :)

Daniel

**Comment by TheoBearman** [comment]
Great news! Please keep me updated on your progress.

Thanks as always...

**Comment by lucidlemon** [comment]
Alright, I have now configured cloudflare for my personal domain where I created a subdomain to serve as a CDN. If you like to you could test it like this:

``` html
<link rel="stylesheet" href="//cdn.danielwinter.at/paradeiser/min/paradeiser.min.css">
```

the cdn.danielwinter.at/paradeiser/ is relative to the dist directory, therefore it provides everything that bower does as well. It works through http and https so.. in theory it should be good to go. I might want to test for further instanced however.

**Comment by TheoBearman** [comment]
Will test shortly.

**Comment by TheoBearman** [comment]
All looks good to me. Using the CDN link on both of my domains with Paradeiser installed and it all seems to be good.

**Comment by lucidlemon** [comment]
Perfect. Thanks for your support.

**Comment by lucidlemon** [comment]
Paradeiser is now available on cdnjs as well, and you may even get each version of it here:
https://cdnjs.com/libraries/paradeiser
