### ISSUE TITLE
demo page links to source code

### ISSUE THREAD

**Issue by Amomo** [lucidlemon/paradeiser#15]
Hi
I would like to see the demo of `Automatic hiding of the navbar using Headroom.js` on paradeiser's website, but it links to the [source code of demo page](https://github.com/lucidlemon/paradeiser/blob/master/demo/demo5.html).

I think maybe "demo5.html" should move to gh-pages branch.
So that we could see the demo directly on browser.

Thanks!

**Comment by Amomo** [comment]
Hi @lucidlemon 
Thanks for your repair immediately!
But...I was saying this site http://lucidlemon.github.io/paradeiser/ 😅

**Comment by lucidlemon** [comment]
Haha yeah, noticed it after editing it. Just added the links, now I just have to wait for githubs cache to clear ;)

**Comment by Amomo** [comment]
Oh I see it! Thanks! :+1:
