### ISSUE TITLE
CSS for .paradeiser ul effects all unordered lists within nav

### ISSUE THREAD

**Issue by macsupport** [lucidlemon/paradeiser#20]
I want to have a materialize dropdown list in my paradeiser menu as one of my links but the css for `.paradeiser ul`  effects all unordered lists within the menu and breaks my dropdown. A change to `.paradeiser ul.paradeiser_children` would allow other unordered lists within the menu, such as button dropdowns etc.

**Comment by lucidlemon** [comment]
mhm. might work as long as everyone is applying the correct class. I will further investigate on this this week.

**Comment by cbsorrilha** [comment]
have someone fixed that?

**Comment by macsupport** [comment]
Any progress on this? You just need to set a specific class for the paradeiser ul to make it not effect every ul in the menu. I did it, but others may not want to change the css to get it  to work.

**Comment by lucidlemon** [comment]
fixed with 03b80d5f0061842847e557a97eca88377a834d5f
