### ISSUE TITLE
Paradeiser not working properly on small screens

### ISSUE THREAD

**Issue by M0nica** [lucidlemon/paradeiser#6]
Paradesier is not working properly for me on small screens (specifically iPad Mini and iPhone 5). It breaks. I am not sure if some of my CSS is conflicting with Paradesier. If you could nudge me in the right direction I would greatly appreciate it!

my site lives at: http://aboutmonica.com/siterehaul/#

actual output of paradeiser looks off on smaller screens ![unnamed](https://cloud.githubusercontent.com/assets/6998954/9394628/78703b06-4757-11e5-8343-c0a97ce9a54c.png)

when I use web dev tools Paradeiser displays correctly
![screen shot 2015-08-17 at 6 10 49 pm](https://cloud.githubusercontent.com/assets/6998954/9394631/7b12dcb0-4757-11e5-8a0c-a245d026ebb1.png)

**Comment by lucidlemon** [comment]
Hi Monica,
Please try including the paradeiser.min.css instead of the paradeiser.css, this should fix it.
The .min.css is vendor prefixed and therefore works within safari.

Nice Website btw.

Daniel

**Comment by M0nica** [comment]
Thank you, Daniel. Using the minified version resolved the issue I was experiencing.
