### ISSUE TITLE
Option to Hide the Navigation Bar During Scroll

### ISSUE THREAD

**Issue by TheoBearman** [lucidlemon/paradeiser#9]
Love love love this plugin. Just wondering if the above could be implemented and then it would be perfect!

**Comment by lucidlemon** [comment]
Hi, I just implemented a basic idea of hiding on scroll using [Headroom.js](https://github.com/WickyNilliams/headroom.js), see [demo 4](https://github.com/lucidlemon/paradeiser/blob/master/demo/demo4.html) for details on the implementation (lines 134 to 141, the rest stays the same).
The overflow menu is still buggy with this solution though, I will fix this soon.

Thanks a lot for your support!

**Comment by TheoBearman** [comment]
This is good but only when the dropdown is being used. I am using paradeiser in two instances. One with the dropdown included and one without.

**Comment by lucidlemon** [comment]
See [demo 5](https://github.com/lucidlemon/paradeiser/blob/master/demo/demo5.html) for an implementation without the overflow button :)

**Comment by TheoBearman** [comment]
Working. Thanks!

**Comment by lucidlemon** [comment]
No Problem! Let me know if I can help you any further and feel free to post links where you are using paradeiser to @dkreide, as I'd love to make a collection of sites that use it.

**Comment by TheoBearman** [comment]
Done!
